name: Build And Run Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make nasm build-essential gcc grub-pc-bin xorriso grub-common mtools qemu-system-x86 

    - name: Build x86_64
      run: make build-x86_64

    - name: Run x86_64
      run: timeout 10 qemu-system-x86_64 -cdrom dist/x86_64/kernel.iso -nographic || true

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Image
        path: dist/x86_64/kernel.iso